services:
  node:
    build: .
    deploy:
      replicas: 1
    environment:
      IS_BOOTSTRAP_NODE: false
      BOOTSTRAP_PORT: ${PORT}
      PORT: ${PORT}
    depends_on:
      - bootstrap-node
    ports:
      - ${PORT}
    volumes:
      - .:/app
  bootstrap-node:
    build: .
    ports:
      - ${PORT}:${PORT}
    environment:
      IS_BOOTSTRAP_NODE: true
      BOOTSTRAP_PORT: ${PORT}
      PORT: ${PORT}

