services:
  node:
    build: .
    deploy:
      replicas: 5
    environment:
      BOOTSTRAP_PORT: 8008
    depends_on:
      - bootstrap-node
  bootstrap-node:
    build: .
    ports:
      - 8008:8008

